### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by briantopping** [wandoulabs/chana#27]
Getting errors building. Anything I can check on my local environment?

```
Brians-MBP:chana brian$ sbt publishLocal publishM2
[info] Loading global plugins from /Users/brian/.sbt/0.13/plugins
[info] Loading project definition from /Users/brian/dev/chana/project
[info] Set current project to chana (in build file:/Users/brian/dev/chana/)
[info] Avro compiler using stringType=String
[info] Formatting 14 Scala sources {file:/Users/brian/dev/chana/}chana-avro(compile) ...
[info] Compiling Avro schema /Users/brian/dev/chana/chana-avro/src/test/resources/avsc/Record.avsc
[info] Packaging /Users/brian/dev/chana/chana-avro/target/scala-2.11/chana-avro_2.11-0.2.0-SNAPSHOT-sources.jar ...
[info] Packaging /Users/brian/dev/chana/target/scala-2.11/chana_2.11-0.2.0-SNAPSHOT-sources.jar ...
[info] Updating {file:/Users/brian/dev/chana/}chana-avro...
[info] Formatting 81 Scala sources {file:/Users/brian/dev/chana/}chana(compile) ...
[info] Done packaging.
[info] Done packaging.
[info] Resolving org.apache.avro#avro;1.7.7 ...
[info] Rats! got a .rats file /Users/brian/dev/chana/chana-avro/src/main/scala/chana/xpath/rats/XPathGrammar.rats
[info] Rats! got a .rats file /Users/brian/dev/chana/src/main/scala/chana/jpql/rats/JPQLGrammar.rats
[info] Resolving org.apache.commons#commons-compress;1.4.1 ...
[info] Running Rats! on /Users/brian/dev/chana/chana-avro/src/main/scala/chana/xpath/rats/XPathGrammar.rats, input from /Users/brian/dev/chana/chana-avro/src/main/scala/chana/xpath/rats and /Users/brian/dev/chana/chana-avro/target/sbt-rats, output to /Users/brian/dev/chana/chana-avro/target/sbt-rats/chana/xpath/rats
[info] Running Rats! on /Users/brian/dev/chana/src/main/scala/chana/jpql/rats/JPQLGrammar.rats, input from /Users/brian/dev/chana/src/main/scala/chana/jpql/rats and /Users/brian/dev/chana/target/sbt-rats, output to /Users/brian/dev/chana/target/sbt-rats/chana/jpql/rats
[info] Resolving com.fasterxml.jackson.core#jackson-core;2.6.3 ...
xtc.tree.VisitorException: Internal error while visiting node xtc.parser.OrderedChoice@7b674838 with visitor xtc.parser.Resolver@92a033c
	at xtc.parser.Resolver.visit(Resolver.java:1918)
	at xtc.parser.Resolver.visit(Resolver.java:1943)
	at xtc.parser.Resolver.visit(Resolver.java:1908)
	at xtc.parser.Resolver.visit(Resolver.java:1903)
	at xtc.parser.Analyzer.process(Analyzer.java:1278)
	at xtc.parser.Resolver.check(Resolver.java:1034)
	at xtc.parser.Resolver.visit(Resolver.java:1739)
	at xtc.parser.Rats.process(Rats.java:292)
	at xtc.util.Tool.run(Tool.java:548)
	at SBTRatsPluginPatched$.runRatsImpl(SBTRatsPlugin.scala:437)
	at SBTRatsPluginPatched$.runGeneratorsImpl(SBTRatsPlugin.scala:214)
	at SBTRatsPluginPatched$$anonfun$runGenerators$1$$anonfun$12.apply(SBTRatsPlugin.scala:153)
	at SBTRatsPluginPatched$$anonfun$runGenerators$1$$anonfun$12.apply(SBTRatsPlugin.scala:152)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
	at SBTRatsPluginPatched$$anonfun$runGenerators$1.apply(SBTRatsPlugin.scala:158)
	at SBTRatsPluginPatched$$anonfun$runGenerators$1.apply(SBTRatsPlugin.scala:144)
	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:35)
	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.1 ...
[info] Done updating.
[info] Updating {file:/Users/brian/dev/chana/}chana...
[info] Wrote /Users/brian/dev/chana/chana-avro/target/scala-2.11/chana-avro_2.11-0.2.0-SNAPSHOT.pom
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.1 ...
[info] Done updating.
[info] :: delivering :: com.wandoulabs.chana#chana-avro_2.11;0.2.0-SNAPSHOT :: 0.2.0-SNAPSHOT :: integration :: Sun Mar 13 16:42:03 MDT 2016
[info] 	delivering ivy file to /Users/brian/dev/chana/chana-avro/target/scala-2.11/ivy-0.2.0-SNAPSHOT.xml
[info] Wrote /Users/brian/dev/chana/target/scala-2.11/chana_2.11-0.2.0-SNAPSHOT.pom
[info] :: delivering :: com.wandoulabs.chana#chana_2.11;0.2.0-SNAPSHOT :: 0.2.0-SNAPSHOT :: integration :: Sun Mar 13 16:42:03 MDT 2016
[info] 	delivering ivy file to /Users/brian/dev/chana/target/scala-2.11/ivy-0.2.0-SNAPSHOT.xml
java.lang.RuntimeException: Rats!, can't find generated file /Users/brian/dev/chana/target/sbt-rats/chana/jpql/rats/JPQLGrammar.java
	at scala.sys.package$.error(package.scala:27)
	at SBTRatsPluginPatched$.runRatsImpl(SBTRatsPlugin.scala:478)
	at SBTRatsPluginPatched$.runGeneratorsImpl(SBTRatsPlugin.scala:214)
	at SBTRatsPluginPatched$$anonfun$runGenerators$1$$anonfun$12.apply(SBTRatsPlugin.scala:153)
	at SBTRatsPluginPatched$$anonfun$runGenerators$1$$anonfun$12.apply(SBTRatsPlugin.scala:152)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
	at SBTRatsPluginPatched$$anonfun$runGenerators$1.apply(SBTRatsPlugin.scala:158)
	at SBTRatsPluginPatched$$anonfun$runGenerators$1.apply(SBTRatsPlugin.scala:144)
	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:35)
	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Rats! failed
	at scala.sys.package$.error(package.scala:27)
	at SBTRatsPluginPatched$.runRatsImpl(SBTRatsPlugin.scala:446)
	at SBTRatsPluginPatched$.runGeneratorsImpl(SBTRatsPlugin.scala:214)
	at SBTRatsPluginPatched$$anonfun$runGenerators$1$$anonfun$12.apply(SBTRatsPlugin.scala:153)
	at SBTRatsPluginPatched$$anonfun$runGenerators$1$$anonfun$12.apply(SBTRatsPlugin.scala:152)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
	at SBTRatsPluginPatched$$anonfun$runGenerators$1.apply(SBTRatsPlugin.scala:158)
	at SBTRatsPluginPatched$$anonfun$runGenerators$1.apply(SBTRatsPlugin.scala:144)
	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:35)
	at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (chana/compile:managedSources) Rats!, can't find generated file /Users/brian/dev/chana/target/sbt-rats/chana/jpql/rats/JPQLGrammar.java
[error] (chana-avro/compile:managedSources) Rats! failed
[error] Total time: 5 s, completed Mar 13, 2016 4:42:03 PM
```

**Comment by briantopping** [comment]
Never mind. I didn't realize standard `publish*` commands did not work here. Works fine with `sbt clean compile list`.
